/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author IlhamLesmana
 */
public class kalkulator_sederhana1 extends javax.swing.JFrame {
 String angka;  Double total,angka1,angka2;  int pilih; 
    /**
     * Creates new form Form_Ukk_Kalkulator
     */
    public kalkulator_sederhana1() {
        initComponents();
         angka=""; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdtampil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmdmod = new javax.swing.JButton();
        cmdlog = new javax.swing.JButton();
        cmdcos = new javax.swing.JButton();
        cmdtan = new javax.swing.JButton();
        cmdsin = new javax.swing.JButton();
        cmdcosh = new javax.swing.JButton();
        cmdtanh = new javax.swing.JButton();
        cmdsinh = new javax.swing.JButton();
        cmdphi = new javax.swing.JButton();
        cmdpangkat10 = new javax.swing.JButton();
        cmd4 = new javax.swing.JButton();
        cmd7 = new javax.swing.JButton();
        cmd1 = new javax.swing.JButton();
        cmd0 = new javax.swing.JButton();
        cmdpangkat2 = new javax.swing.JButton();
        cmdpangkat3 = new javax.swing.JButton();
        cmd8 = new javax.swing.JButton();
        cmd2 = new javax.swing.JButton();
        cmdtitik = new javax.swing.JButton();
        cmd5 = new javax.swing.JButton();
        cmdplusmin = new javax.swing.JButton();
        cmd9 = new javax.swing.JButton();
        cmdpangkaty = new javax.swing.JButton();
        cmd3 = new javax.swing.JButton();
        cmd6 = new javax.swing.JButton();
        cmdtambah = new javax.swing.JButton();
        cmdkurang = new javax.swing.JButton();
        cmdtab = new javax.swing.JButton();
        cmdkali = new javax.swing.JButton();
        cmdbagi = new javax.swing.JButton();
        cmdsamadengan = new javax.swing.JButton();
        cmdbagix = new javax.swing.JButton();
        cmdclear = new javax.swing.JButton();
        cmdpersen = new javax.swing.JButton();
        cmdakar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Georgia", 3, 38)); // NOI18N
        jLabel1.setText("Kalkulator Sederhana");

        cmdmod.setText("Mod");
        cmdmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdmodActionPerformed(evt);
            }
        });

        cmdlog.setText("Log");
        cmdlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdlogActionPerformed(evt);
            }
        });

        cmdcos.setText("Cos");
        cmdcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcosActionPerformed(evt);
            }
        });

        cmdtan.setText("Tan");
        cmdtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdtanActionPerformed(evt);
            }
        });

        cmdsin.setText("Sin");

        cmdcosh.setText("Cosh");
        cmdcosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcoshActionPerformed(evt);
            }
        });

        cmdtanh.setText("Tanh");
        cmdtanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdtanhActionPerformed(evt);
            }
        });

        cmdsinh.setText("Sinh");
        cmdsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsinhActionPerformed(evt);
            }
        });

        cmdphi.setText("Phi");
        cmdphi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdphiActionPerformed(evt);
            }
        });

        cmdpangkat10.setText("10^x");
        cmdpangkat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpangkat10ActionPerformed(evt);
            }
        });

        cmd4.setText("4");
        cmd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd4ActionPerformed(evt);
            }
        });

        cmd7.setText("7");
        cmd7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd7ActionPerformed(evt);
            }
        });

        cmd1.setText("1");
        cmd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd1ActionPerformed(evt);
            }
        });

        cmd0.setText("0");
        cmd0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd0ActionPerformed(evt);
            }
        });

        cmdpangkat2.setText("x^2");
        cmdpangkat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpangkat2ActionPerformed(evt);
            }
        });

        cmdpangkat3.setText("x^3");
        cmdpangkat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpangkat3ActionPerformed(evt);
            }
        });

        cmd8.setText("8");
        cmd8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd8ActionPerformed(evt);
            }
        });

        cmd2.setText("2");
        cmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd2ActionPerformed(evt);
            }
        });

        cmdtitik.setText(".");
        cmdtitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdtitikActionPerformed(evt);
            }
        });

        cmd5.setText("5");
        cmd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd5ActionPerformed(evt);
            }
        });

        cmdplusmin.setText("+/-");
        cmdplusmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdplusminActionPerformed(evt);
            }
        });

        cmd9.setText("9");
        cmd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd9ActionPerformed(evt);
            }
        });

        cmdpangkaty.setText("x^y");
        cmdpangkaty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpangkatyActionPerformed(evt);
            }
        });

        cmd3.setText("3");
        cmd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd3ActionPerformed(evt);
            }
        });

        cmd6.setText("6");
        cmd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd6ActionPerformed(evt);
            }
        });

        cmdtambah.setText("+");
        cmdtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdtambahActionPerformed(evt);
            }
        });

        cmdkurang.setText("-");
        cmdkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdkurangActionPerformed(evt);
            }
        });

        cmdtab.setText("<--Tab");
        cmdtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdtabActionPerformed(evt);
            }
        });

        cmdkali.setText("*");
        cmdkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdkaliActionPerformed(evt);
            }
        });

        cmdbagi.setText("/");
        cmdbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbagiActionPerformed(evt);
            }
        });

        cmdsamadengan.setText("=");
        cmdsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsamadenganActionPerformed(evt);
            }
        });

        cmdbagix.setText("1/x");
        cmdbagix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbagixActionPerformed(evt);
            }
        });

        cmdclear.setText("Clear");
        cmdclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdclearActionPerformed(evt);
            }
        });

        cmdpersen.setText("%");
        cmdpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpersenActionPerformed(evt);
            }
        });

        cmdakar.setText("Akar");
        cmdakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdakarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdmod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdtan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdcos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdlog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdsin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdphi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdtanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdcosh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdpangkat10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmd7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdpangkat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmd8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdpangkat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdtitik, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmd9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdpangkaty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdplusmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdbagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdkali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdtab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdakar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdpersen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdbagix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdsamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdtampil)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdtampil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cmdlog)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdmod)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdtan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdcos)
                            .addGap(34, 34, 34))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cmdpangkat10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdphi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdtanh)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdcosh)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmdsin)
                                .addComponent(cmdsinh)
                                .addComponent(cmd0)
                                .addComponent(cmdtitik)
                                .addComponent(cmdplusmin)
                                .addComponent(cmdtambah)
                                .addComponent(cmdsamadengan))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdpangkat2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdpangkat3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdpangkaty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmd3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdtab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdbagi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdkali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdkurang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdclear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdakar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdpersen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdbagix)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdlogActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.log(r);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdlogActionPerformed

    private void cmdpangkat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpangkat10ActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.pow(10,r);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdpangkat10ActionPerformed

    private void cmdpangkat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpangkat2ActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.pow(r,2);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdpangkat2ActionPerformed

    private void cmdpangkat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpangkat3ActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.pow(r,3);
angka = Double.toString(total);
cmdtampil.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_cmdpangkat3ActionPerformed

    private void cmdpangkatyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpangkatyActionPerformed
angka1 = Double.parseDouble(angka);
cmdtampil.setText(cmdtampil.getText()+"^");
angka="";
pilih=5;
// TODO add your handling code here:
    }//GEN-LAST:event_cmdpangkatyActionPerformed

    private void cmdtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdtabActionPerformed
angka = angka.substring(1, angka.length()-0);
cmdtampil.setText(angka);// TODO add your handling code here:
    }//GEN-LAST:event_cmdtabActionPerformed

    private void cmdclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdclearActionPerformed
cmdtampil.setText("");
angka1=0.0;
angka2=0.0;
total=0.0;
angka=("");// TODO add your handling code here:
    }//GEN-LAST:event_cmdclearActionPerformed

    private void cmdtitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdtitikActionPerformed
angka+=".";
cmdtampil.setText(cmdtampil.getText()+cmdtitik.getText());// TODO add your handling code here:
    }//GEN-LAST:event_cmdtitikActionPerformed

    private void cmdplusminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdplusminActionPerformed
angka=""+angka;
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdplusminActionPerformed

    private void cmd0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd0ActionPerformed
angka +="0"; cmdtampil.setText(cmdtampil.getText()+cmd0.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd0ActionPerformed

    private void cmd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd1ActionPerformed
angka +="1"; cmdtampil.setText(cmdtampil.getText()+cmd1.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd1ActionPerformed

    private void cmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd2ActionPerformed
angka +="2"; cmdtampil.setText(cmdtampil.getText()+cmd2.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd2ActionPerformed

    private void cmd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd3ActionPerformed
angka +="3"; cmdtampil.setText(cmdtampil.getText()+cmd3.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd3ActionPerformed

    private void cmd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd4ActionPerformed
angka +="4"
        + ""; cmdtampil.setText(cmdtampil.getText()+cmd4.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd4ActionPerformed

    private void cmd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd5ActionPerformed
angka +="5"; cmdtampil.setText(cmdtampil.getText()+cmd5.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd5ActionPerformed

    private void cmd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd6ActionPerformed
angka +="6"; cmdtampil.setText(cmdtampil.getText()+cmd6.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd6ActionPerformed

    private void cmd7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd7ActionPerformed
angka +="7"; cmdtampil.setText(cmdtampil.getText()+cmd7.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd7ActionPerformed

    private void cmd8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd8ActionPerformed
angka +="8"; cmdtampil.setText(cmdtampil.getText()+cmd8.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd8ActionPerformed

    private void cmd9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd9ActionPerformed
angka +="9"; cmdtampil.setText(cmdtampil.getText()+cmd9.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_cmd9ActionPerformed

    private void cmdtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdtambahActionPerformed
angka1=Double.parseDouble(angka); cmdtampil.setText("+"); angka=""; pilih=1;         // TODO add your handling code here:
    }//GEN-LAST:event_cmdtambahActionPerformed

    private void cmdkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdkurangActionPerformed
angka1=Double.parseDouble(angka); cmdtampil.setText("-"); angka=""; pilih=2;         // TODO add your handling code here:
    }//GEN-LAST:event_cmdkurangActionPerformed

    private void cmdkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdkaliActionPerformed
angka1=Double.parseDouble(angka); cmdtampil.setText("*"); angka=""; pilih=3;     }//GEN-LAST:event_cmdkaliActionPerformed

    private void cmdbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbagiActionPerformed
angka1=Double.parseDouble(angka); cmdtampil.setText("/"); angka=""; pilih=4;         // TODO add your handling code here:
    }//GEN-LAST:event_cmdbagiActionPerformed

    private void cmdsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsamadenganActionPerformed
switch(pilih)
{
            case 1:
            angka2=Double.parseDouble(angka);
            total = angka1+angka2;
            angka = Double.toString(total);
            cmdtampil.setText(angka);
            break;
            case 2:
                angka2=Double.parseDouble(angka);
                total = angka1-angka2;
                angka = Double.toString(total);
                cmdtampil.setText(angka);
                break;
            case 3:
                angka2=Double.parseDouble(angka);
                total = angka1*angka2;
                angka = Double.toString(total);
                cmdtampil.setText(angka);
                break;  
            case 4:
                angka2=Double.parseDouble(angka);
                total = angka1/angka2;
                angka = Double.toString(total);
                cmdtampil.setText(angka);
                break;
            case 5:
                angka2=Double.parseDouble(angka);
                total = Math.pow(angka1,angka2);
                angka = Double.toString(total);
                cmdtampil.setText(angka);
                break; 
            case 6:
                angka2=Double.parseDouble(angka);
                total = angka1%angka2;
                angka = Double.toString(total);
                cmdtampil.setText(angka);
                break;  
                
}
// TODO add your handling code here:
    }//GEN-LAST:event_cmdsamadenganActionPerformed

    private void cmdmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdmodActionPerformed

angka1 = Double.parseDouble(angka);
cmdtampil.setText(cmdtampil.getText()+cmdmod.getText());
angka="";
pilih=6;// TODO add your handling code here:
    }//GEN-LAST:event_cmdmodActionPerformed

    private void cmdphiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdphiActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.PI * r;
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdphiActionPerformed

    private void cmdtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdtanActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.tan(r);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdtanActionPerformed

    private void cmdcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcosActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.cos(r);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdcosActionPerformed

    private void cmdcoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcoshActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.cosh(r);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdcoshActionPerformed

    private void cmdtanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdtanhActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.tanh(r);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdtanhActionPerformed

    private void cmdakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdakarActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.sqrt(r);
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdakarActionPerformed

    private void cmdbagixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbagixActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = 1/r;
angka = Double.toString(total);
cmdtampil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdbagixActionPerformed

    private void cmdpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpersenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdpersenActionPerformed

    private void cmdsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsinhActionPerformed
double r;
r= Double.valueOf(cmdtampil.getText());
total = Math.sinh(r);
angka = Double.toString(total);
cmdtampil.setText(angka);         // TODO add your handling code here:
    }//GEN-LAST:event_cmdsinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator_sederhana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator_sederhana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator_sederhana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator_sederhana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator_sederhana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd0;
    private javax.swing.JButton cmd1;
    private javax.swing.JButton cmd2;
    private javax.swing.JButton cmd3;
    private javax.swing.JButton cmd4;
    private javax.swing.JButton cmd5;
    private javax.swing.JButton cmd6;
    private javax.swing.JButton cmd7;
    private javax.swing.JButton cmd8;
    private javax.swing.JButton cmd9;
    private javax.swing.JButton cmdakar;
    private javax.swing.JButton cmdbagi;
    private javax.swing.JButton cmdbagix;
    private javax.swing.JButton cmdclear;
    private javax.swing.JButton cmdcos;
    private javax.swing.JButton cmdcosh;
    private javax.swing.JButton cmdkali;
    private javax.swing.JButton cmdkurang;
    private javax.swing.JButton cmdlog;
    private javax.swing.JButton cmdmod;
    private javax.swing.JButton cmdpangkat10;
    private javax.swing.JButton cmdpangkat2;
    private javax.swing.JButton cmdpangkat3;
    private javax.swing.JButton cmdpangkaty;
    private javax.swing.JButton cmdpersen;
    private javax.swing.JButton cmdphi;
    private javax.swing.JButton cmdplusmin;
    private javax.swing.JButton cmdsamadengan;
    private javax.swing.JButton cmdsin;
    private javax.swing.JButton cmdsinh;
    private javax.swing.JButton cmdtab;
    private javax.swing.JButton cmdtambah;
    private javax.swing.JTextField cmdtampil;
    private javax.swing.JButton cmdtan;
    private javax.swing.JButton cmdtanh;
    private javax.swing.JButton cmdtitik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
